name: dynamic_form_builder_example
description: Demo app for dynamic_form_builder.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  dynamic_form_builder:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
