name: json_form_engine_example
description: Demo app for json_form_engine.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  json_form_engine:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
